/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DeSo01.Client;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author traioi
 */
public class TCPClientView extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form TCPClientView
     */
    public TCPClientView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblSoA = new javax.swing.JLabel();
        txtSoA = new javax.swing.JTextField();
        lblSoB = new javax.swing.JLabel();
        txtSoB = new javax.swing.JTextField();
        txtKetQua = new javax.swing.JTextField();
        lblKetQua = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblSoA.setText("Nhap a:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 179, 0, 0);
        getContentPane().add(lblSoA, gridBagConstraints);

        txtSoA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 142;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 129, 0, 0);
        getContentPane().add(txtSoA, gridBagConstraints);

        lblSoB.setText("Nhap b:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 178, 0, 0);
        getContentPane().add(lblSoB, gridBagConstraints);

        txtSoB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoBActionPerformed(evt);
            }
        });
        txtSoB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSoBKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 142;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 129, 0, 0);
        getContentPane().add(txtSoB, gridBagConstraints);

        txtKetQua.setEditable(false);
        txtKetQua.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtKetQua.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKetQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKetQuaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 184;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 112, 0, 0);
        getContentPane().add(txtKetQua, gridBagConstraints);

        lblKetQua.setText("Boi chung nho nhat cua a va b");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 100, 0, 88);
        getContentPane().add(lblKetQua, gridBagConstraints);

        btnSubmit.setText("Submit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 161, 48, 0);
        getContentPane().add(btnSubmit, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoBActionPerformed

    private void txtKetQuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKetQuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKetQuaActionPerformed

    private void txtSoBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoBKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoBKeyPressed
    
    public void actionPerformed(ActionEvent e) {}
    
    public TCPClientModel getSo() {
      String numA = txtSoA.getText();
      String numB = txtSoB.getText();
      TCPClientModel model = new TCPClientModel(numA, numB);
      return model;
    }
    
    public void getKetQua(String result){
      txtKetQua.setText(result);
    }
    
    public void btnSubmitListener(ActionListener sub) {
      btnSubmit.addActionListener(sub);
    } 
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblKetQua;
    private javax.swing.JLabel lblSoA;
    private javax.swing.JLabel lblSoB;
    private javax.swing.JTextField txtKetQua;
    private javax.swing.JTextField txtSoA;
    private javax.swing.JTextField txtSoB;
    // End of variables declaration//GEN-END:variables
}
